In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd  
from tqdm import tqdm 
import numba 
import os

In [36]:
file_name_a = r"practice_2022\data\a_an_example.in.txt"
file_name_b = r"practice_2022\data\b_basic.in.txt"
file_name_c= r"practice_2022\data\c_coarse.in.txt"
file_name_d = r"practice_2022\data\d_difficult.in.txt"
file_name_e = r"practice_2022\data\e_elaborate.in.txt"

In [48]:
def load(file_name):
    with open(file_name, 'r') as file:
        # Read first line 
        N = int(file.readline())

        print(f"Loading {N} Customers")
        likes = []
        avg_l = []
        for i in range(N):
            line = file.readline().rstrip().split(" ")
            likes.extend(line[1:])
        
        dislikes = []
        for i in range(N):
            line = file.readline().rstrip().split(" ")
            dislikes.extend(line[1:])

        return likes, dislikes


In [49]:
def get_uniques(likes, dislikes):
    l, lc = np.unique(np.array(likes).flatten(), return_counts=True)
    d, dc = np.unique(np.array(dislikes).flatten(), return_counts=True)

    a, ac = np.unique(np.array(likes + dislikes).flatten(), return_counts=True)

    print(f"Unique likes, dislikes: {len(l)}, {len(d)}")
    print(f"Unique from likes + dislikes: {len(a)}")

    return (l, lc), (d, dc), (a, ac)

### Uniques

In [50]:
la, da = load(file_name_a)
ua = get_uniques(la, da)
ua

Loading 3 Customers
Unique likes, dislikes: 3, 4
Unique from likes + dislikes: 6


((array(['basil', 'cheese', 'peppers'], dtype='<U7'),
  array([1, 1, 1], dtype=int64)),
 (array(['basil', 'mushrooms', 'pineapple', 'tomatoes'], dtype='<U9'),
  array([1, 1, 1, 1], dtype=int64)),
 (array(['basil', 'cheese', 'mushrooms', 'peppers', 'pineapple', 'tomatoes'],
        dtype='<U9'),
  array([2, 1, 1, 1, 1, 1], dtype=int64)))

In [51]:
lb, db = load(file_name_b)
ua = get_uniques(lb, db)

Loading 5 Customers
Unique likes, dislikes: 4, 3
Unique from likes + dislikes: 6


In [52]:
lc, dc = load(file_name_c)
ua = get_uniques(lc, dc)

Loading 10 Customers
Unique likes, dislikes: 9, 10
Unique from likes + dislikes: 10


In [55]:
ld, dd = load(file_name_d)
ua = get_uniques(ld, dd)

Loading 9368 Customers
Unique likes, dislikes: 600, 600
Unique from likes + dislikes: 600


In [54]:
le, de = load(file_name_e)
ua = get_uniques(le, de)

Loading 4986 Customers
Unique likes, dislikes: 7833, 7781
Unique from likes + dislikes: 10000
